### ISSUE TITLE
CallbackPaths not defined

### ISSUE THREAD

**Issue by ghost** [aspnet-contrib/AspNet.Security.OpenId.Providers#110]
**Describe the bug**
Sample project `Mvc.Client` does not work because the callback paths are not defined (e.g. `"/signin-stackexchange"`)

**Steps To reproduce**
Run `Mvc.Client` and click `Connect using StackExchange`, enter credentials.

**Expected behaviour**
The sample should "work". It should contain a sample implementation for the callback routes.

**Actual behaviour**
After logging in to OpenId provider I am returned to `http://localhost:54540/signin-stackexchange` which results in ``HTTP ERROR 500``. (Actually I am surprised that it is not a 404)

**System information:**
 - OS:  Windows 10
 - Library Version: 5.0.0
 - .NET version: 5.0.201

**Comment by kevinchalet** [comment]
> The sample should "work". It should contain a sample implementation for the callback routes.

The OpenID provider handles these requests for you. The issue was caused by a same-site issue with the antiforgery. I fixed it by enabling TLS to ensure `lax` can be used for the antiforgery cookie: https://github.com/aspnet-contrib/AspNet.Security.OpenId.Providers/commit/a5b16422a07c9652c3dc89fbf13ec71dbc974554.

**Comment by ghost** [comment]
I have no clue what `lax` is but it works now. Thanks!
