### ISSUE TITLE
OAuth with Steam and user data

### ISSUE THREAD

**Issue by Xarkam** [aspnet-contrib/AspNet.Security.OpenId.Providers#68]
**Describe the bug**
email is used for fields UserName and NormalizedUserName in AspNetUsers table.

**Steps To reproduce**
Regsiter to sample with steam account

**Expected behaviour**
Use the Steam username and not his email because you can't modify username by IdentityUI

**Actual behaviour**
Because a picture is better than a long speech:
![image](https://user-images.githubusercontent.com/331816/66829875-95248280-ef54-11e9-971b-775c50253e51.png)

**System information:**
 - OS: Windows 10
 - Library Version 3.0.0
 - .NET version 3.0

**Additional context**
My application is a Blazor server app.

Can you make Steam OpenID provider documentation ?

**Comment by martincostello** [comment]
Based on our tests, the user name (`NameIdentifier`) contains the `steamid` for the user:

https://github.com/aspnet-contrib/AspNet.Security.OpenId.Providers/blob/87f10d306770b6fef4eca4e290aa7743eb7adfff/test/AspNet.Security.OpenId.Providers.Tests/Steam/SteamTests.cs#L42

Not to say that's correct, but that was the existing behaviour when I added the tests.

We don't otherwise appear to explicitly set what the username should be as far as I can tell.

I guess you could either register a callback for the `Authenticated` event and customise the claims further yourself, otherwise maybe there's something that needs changing in your identity configuration?

https://github.com/aspnet-contrib/AspNet.Security.OpenId.Providers/blob/85b473a20750e0ea44ad13507afe99f577fcb2c8/src/AspNet.Security.OpenId.Steam/SteamAuthenticationHandler.cs#L126

**Comment by postb99** [comment]
Hi @martincostello I'm Xarkam's wife and just did some other successless tries, we're working together.
What we'd like to do is similar to: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/additional-claims?view=aspnetcore-3.0
because we agree that the user name isn't known and would come from Steam, while the e-mail is stored in Identity DB. However, the Username of the screenshot should really display the (uneditable) Steam user name.

I've setup some code for the following events: `OnAuthenticated` and `OnTicketReceived`. I've noticed that in both cases, the Steam user claims are set as expected in the event handler's context (the NameIdentifier (Steam user id)  and the Name (Steam user name)) but the Identity user is not set yet (in event handler's context -> HttpContext -> User). However, when our app page displays, the Identity user claims are displayed, and only them.

This made me try to add a custom implementation of `UserClaimsPrincipalFactory`, not sure if it's the way to go (how to inject the Steam authentication context?).

We really miss a documentation, because the way to setup `AddSteam()` isn't clear and even stated. It works all with trial and error, knowledge of OpenId, playing with Intellisense... looking at documentation for other providers (my link above).

Thank you for helping.

Our Identity configuration:

```
services.AddDbContext ...

            services.AddDefaultIdentity<IdentityUser>()
                .AddRoles<IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>();
                //.AddSignInManager<SignInManager<IdentityUser>>()
                //.AddRoleManager<RoleManager<IdentityRole>>();
 
 ...
            // Use cookies with Identity
            services.ConfigureApplicationCookie(options =>
            {
                options.LoginPath = "/login";
                options.LogoutPath = "/signout";
            });

            services.AddAuthentication(options =>
                    {
                        // Use application cookies
                        options.DefaultAuthenticateScheme = IdentityConstants.ApplicationScheme;
                    })
                .AddSteam(options =>
                {
                    options.ApplicationKey = "^^SECRET^^";
                    options.SaveTokens = true;
                    options.Events.OnTicketReceived = context_ =>
                    {
                        var steamUserAsClaims = context_.Principal;
                        var identityUser = context_.HttpContext.User;

                        return Task.CompletedTask;

                    };
                    options.Events.OnAuthenticated = context_ =>
                    {
                        var steamUserAsClaims = context_.Identity;
                        var nameIdentifier = steamUserAsClaims.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value;
                        var name = steamUserAsClaims.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Name)?.Value;

                        // NOPE: Identity user not initialized yet in context_.HttpContext.User

                        context_.HttpContext.User.Claims.Append(new Claim(ClaimTypes.NameIdentifier, nameIdentifier));
                        context_.HttpContext.User.Claims.Append(new Claim(ClaimTypes.Name, name));

                        return Task.CompletedTask;
                    };
                });
```

**Comment by martincostello** [comment]
I'll try and have a look later this evening when I get the chance, but in the meantime if it helps, here's a link to a custom claims factory of my own I use in a website that uses our Amazon OAuth package: https://github.com/martincostello/alexa-london-travel-site/blob/master/src/LondonTravel.Site/Identity/UserClaimsPrincipalFactory.cs

**Comment by postb99** [comment]
Hi @martincostello please can you be kind and check the Identity configuration we submitted to you as you promised, as  we think something is wrong because right after successful Steam login, there is no Identity user set. So we can go forward. Thank you very much.

**Comment by martincostello** [comment]
Sorry for the delay in replying.

Unfortunately without the code in question to debug and a working configuration for Stream, I'm not sure what I can do to help debug this code and find the solution for you.

The only things I can suggest are:

  1. Consider custom mapping the claims using the claims actions to re-map the claims to what you'd like then to be.
  1. Use a custom claims principal factory as suggested here: https://github.com/aspnet-contrib/AspNet.Security.OpenId.Providers/issues/68#issuecomment-542574605

Otherwise I'm not sure, and as the issue appears to be with ASP.NET Identity and EntityFramework, rather than the Steam OAuth provider, I'm not sure your issue is within the scope of this project.

**Comment by postb99** [comment]
Thanks, I will check with Identity  project then, since I have an Identity configuration issue.
